### ISSUE TITLE
Create Procedure for Tracking Social Media Engagement

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/public-haus#9]
https://public-haus.pages.dev/procedures/social

- [x] Write [Tracking Social Media Engagement](https://hackmd.io/rq3soKU4RzGMsr3NQ62efw) procedure (2 hours)
- [x] Test procedure with April, May, June (1 hour)
- [x] Move procedure to Vocs (.25 hour)
- [x] Deploy updates (.25 hour)

**Total**: 3.5 hours
